name: Testing github pages
on: push
jobs:
  build:
    name: Build job
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - name: setup step 1
        uses: actions/setup-python@v1
        with:
          python-version: 3.7